# 트레이닝

In [20]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import keras.backend as K
from keras.models import Sequential,model_from_json #케라스 딥러닝 프레임워크 사용
from keras.layers import Dense
from keras.optimizers import SGD, Adam
from sklearn.model_selection import train_test_split
import scipy.io as io

In [21]:
hungry = io.loadmat("hungry_ANN.mat")
spasm = io.loadmat("spasm_ANN.mat")
#SPASM = 1
#HUNGRY = 0
#전처리된 데이터가 저장된 .mat 파일

hungry_dataset = hungry['hungry']
spasm_dataser = spasm['spasm']

dataset=np.row_stack((hungry_dataset,spasm_dataser))
np.random.shuffle(dataset)
ip_shuff = np.delete(dataset, 50, 1)
op_shuff = dataset[:,50]

In [22]:
op_shuff=op_shuff.astype(int)

In [23]:
lis = []
for i in ip_shuff:
    ar = i/max(i)
    lis.extend([ar.tolist()])
ip_shuff_nor = np.array(lis)

In [24]:
X_train, X_test, y_train, y_test = train_test_split(ip_shuff, op_shuff ,
                                                    test_size=0.2,
                                                    random_state=42)

In [25]:
ip_shuff_nor.shape

(400, 50)

In [26]:
K.clear_session()
model = Sequential()
model.add(Dense(25, input_dim=50, activation='sigmoid')) #활성화함수-sigmoid, 25개의 필터
#model.add(Dense(15, activation='sigmoid'))
#model.add(Dense(10, activation='sigmoid'))
model.add(Dense(4, activation='tanh')) #활성화함수-tanh, 4개의 필터
model.add(Dense(1, activation='sigmoid')) #활성화함수-sigmoid, 1개의 필터
#필터링 3번 25-15-10
model.compile(SGD(lr=0.0019), 'binary_crossentropy', metrics=['accuracy'])
#SGD Momentum 최적화
model.fit(X_train, y_train,epochs=100)
# model = Sequential()
# model.add(Dense(25, input_dim=50, activation='relu'))
# #model.add(Dense(64, activation='relu'))
# model.add(Dense(1, activation='sigmoid'))
# model.compile(Adam(lr=0.0019), 'binary_crossentropy', metrics=['accuracy'])
# model.fit(X_train, y_train,epochs=100)
# 훈련을 진행

Epoch 1/100


C:\Users\6eom9eun\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


10/10 [==============================] - 1s 3ms/step - loss: 0.6849 - accuracy: 0.5094
Epoch 2/100
10/10 [==============================] - 0s 3ms/step - loss: 0.6848 - accuracy: 0.5094
Epoch 3/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6846 - accuracy: 0.5094
Epoch 4/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6844 - accuracy: 0.5094
Epoch 5/100
10/10 [==============================] - 0s 3ms/step - loss: 0.6842 - accuracy: 0.5094
Epoch 6/100
10/10 [==============================] - 0s 3ms/step - loss: 0.6841 - accuracy: 0.5094
Epoch 7/100
10/10 [==============================] - 0s 3ms/step - loss: 0.6839 - accuracy: 0.5094
Epoch 8/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6838 - accuracy: 0.5094
Epoch 9/100
10/10 [==============================] - 0s 3ms/step - loss: 0.6836 - accuracy: 0.5094
Epoch 10/100
10/10 [==============================] - 0s 4ms/step - loss: 0.6835 - accuracy: 0.5094
Epoch 11/100
10/10 [=

tanh 함수, (Hyperbolic tangent function)
하이퍼볼릭탄젠트란 쌍곡선 함수중 하나이다.

하이퍼볼릭탄젠트 함수는 sigmoid 함수를 transformation해서 얻을 수 있다.

In [28]:
model.evaluate(X_test, y_test)

3/3 [==============================] - 0s 4ms/step - loss: 0.6697 - accuracy: 0.7500


[0.6696750521659851, 0.75]

In [29]:
model_json = model.to_json()
with open("crybaby.json", "w") as json_file:
    json_file.write(model_json)

In [30]:
from sklearn import svm

In [31]:
clf = svm.SVC()

In [32]:
clf.fit(X_train, y_train) 

SVC()

In [33]:
n=X_train[0].reshape(1, -1)
clf.predict(n)

array([1])

In [34]:
y_test

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [35]:
y_pred = clf.predict(X_test)

In [36]:
y_pred 

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_test,y_pred)

1.0

In [39]:
import joblib
joblib.dump(clf, 'svm.pkl') #학습한 모델 저장

['svm.pkl']