# 분류기
ANN 인공신경망

In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import keras.backend as K
from keras.models import Sequential,model_from_json #케라스 딥러닝 프레임워크 사용
from keras.layers import Dense
from keras.optimizers import SGD, Adam
from sklearn.model_selection import train_test_split
import scipy.io as io

In [8]:
json_file = open('crybaby.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

In [9]:
hungry = io.loadmat("hungry_ANN.mat")
spasm = io.loadmat("spasm_ANN.mat")
#SPASM = 1
#HUNGRY = 0

hungry_dataset = hungry['hungry']
spasm_dataser = spasm['spasm']

dataset=np.row_stack((hungry_dataset,spasm_dataser))
np.random.shuffle(dataset)
ip_shuff = np.delete(dataset, 50, 1)
op_shuff = dataset[:,50]

In [10]:
ip_shuff

array([[0.03934432, 0.10346118, 0.18137671, ..., 0.01819075, 0.01814725,
        0.02331979],
       [0.03575922, 0.1000877 , 0.19131995, ..., 0.01889037, 0.01893793,
        0.02419496],
       [0.01490759, 0.06087052, 0.11980164, ..., 0.07102452, 0.07503042,
        0.07656759],
       ...,
       [0.01655639, 0.06785338, 0.13941284, ..., 0.07091399, 0.0770708 ,
        0.07560672],
       [0.04111476, 0.11004269, 0.18692516, ..., 0.0186188 , 0.01968068,
        0.02613161],
       [0.03429252, 0.09286838, 0.1736114 , ..., 0.0174991 , 0.01756014,
        0.02228377]])

In [5]:
op_shuff #레이블 값

array([1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 1., 0.

In [9]:
loaded_model.predict(ip_shuff)

13/13 [==============================] - 0s 2ms/step


array([[0.7368305 ],
       [0.7311723 ],
       [0.7349098 ],
       [0.7397358 ],
       [0.73398465],
       [0.73868483],
       [0.7375743 ],
       [0.73141944],
       [0.73667604],
       [0.73366344],
       [0.731439  ],
       [0.73950034],
       [0.7393597 ],
       [0.7375148 ],
       [0.73274755],
       [0.73871666],
       [0.7389965 ],
       [0.73729885],
       [0.7322775 ],
       [0.7393708 ],
       [0.7393187 ],
       [0.7392809 ],
       [0.7333743 ],
       [0.7334709 ],
       [0.73541784],
       [0.73295486],
       [0.7375883 ],
       [0.7322134 ],
       [0.7318892 ],
       [0.7371692 ],
       [0.73773396],
       [0.7334227 ],
       [0.7361248 ],
       [0.73033315],
       [0.7375242 ],
       [0.737766  ],
       [0.73678297],
       [0.7339123 ],
       [0.7367215 ],
       [0.7339751 ],
       [0.7387474 ],
       [0.73899233],
       [0.73585534],
       [0.737541  ],
       [0.73497087],
       [0.7396195 ],
       [0.73354757],
       [0.738